version: '3.7'
services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
    ports:
      - "3306:3306"
    volumes:
      - ./.env:/etc/environment
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - conduit

  conduit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conduit
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - conduit

volumes:
    mysql_db:
      driver: local
networks:
  conduit:
    driver: bridge
